### ISSUE TITLE
[FixBug]Perlin noise's shape

### ISSUE THREAD

**Issue by Shiyang980713** [cidcom/SatelliteCloudGenerator#1]
Thank you for your solid work! I found some bugs while using the code.

In [noise.py-line63]
```
out += weight*perlin(int(big_shape[0]/scale), int(big_shape[1]/scale), scale)[:shape[0],:shape[1]]
```
Some input images with specific shapes can cause anomalies in the shape of the generated Perlin noise.
For example, when the input image shape is `torch.Size([829, 1010, 3])`
<img width="367" alt="image" src="https://user-images.githubusercontent.com/57209725/195271757-9a5a9c1e-3ab3-4d05-81f7-b78e94bb2da5.png">
the code will report an error：
'The size of tensor a (1010) must match the size of tensor b (1008) at non-singleton dimension 1'. This bug may be caused by the division of `big shape` and `scale`.
**I fix this with a simple modification:**
```
out += weight*perlin(math.ceil(big_shape[0]/scale), math.ceil(big_shape[1]/scale), scale)[:shape[0],:shape[1]]
```
Then everything is ok.
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/57209725/195273316-8eaf5be2-9cac-4c45-83bd-41e935aefba1.png">

**Comment by mikonvergence** [comment]
Hello, thank you for bringing this to attention, it is greatly appreciated!

So, I just did a quick call of `plt.imshow(add_cloud(torch.rand((829, 1010, 3))))` and it works fine on my side.

<img width="992" alt="Screenshot 2022-10-12 at 08 39 18" src="https://user-images.githubusercontent.com/13435425/195280381-e62664b9-beda-4515-b3f6-d3973ed1e2f6.png">

Can you please share more details about how you yourself called it, so we can understand why it resulted in an error on your side? Also, did you repeatedly get this error or only for some of the calls?

When the internal `scales` variable is filled with values in lines 47-53 (assuming no value is provided in the function arguments), it should create a list of scales with that are powers of 2, and which the smaller value of `shape` can be divided by with no remainder. The `big_shape`, on the other hand, is set up as the nearest powers of 2 close above `shape`, so in this case it should be matched with `(1024,1024)`.

That's why I'm worried that there could be another bug causing this, since the division should be working correctly, without using `ceil`.

**Comment by Shiyang980713** [comment]
Thank you for your reply. 
Sorry, I have just noticed the addition of `up_lim` in the **latest** noise.py-line50. This change should ensure that the code works properly from another perspective.
I can reproduce this error in the *older version* `769dc8f` with:
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/57209725/195295133-863b2ed1-d502-490c-8dfa-fde4865fb8dc.png">

In `769dc8f`,the Perlin noise shape may be smaller than the original image, so the indexing operation `[:shape[0],:shape[1]]` will bring an error.

**Comment by Shiyang980713** [comment]
I noticed the latest `a9e0c22` comment is for 'small images'.
🫢So I tried `a9e0c22`  with:
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/57209725/195298042-26e901b1-ef3e-45ec-9c0c-22311a209d91.png">
This input may not be common, so I'm just mentioning it in passing. chill🤗

**Comment by mikonvergence** [comment]
Alright, that explains it! Indeed, the last commit was made to make this aspect more flexible. It was pushed only 10 days ago so that explains why some people might be working on the older version of the tool.

Can I treat this issue as resolved (since it does not occur in the current version of the project)?

**Comment by Shiyang980713** [comment]
yes, thanks a lot!

**Comment by Shiyang980713** [comment]
> Alright, that explains it! Indeed, the last commit was made to make this aspect more flexible. It was pushed only 10 days ago so that explains why some people might be working on the older version of the tool.
> 
> Can I treat this issue as resolved (since it does not occur in the current version of the project)?

yes, thanks a lot!

**Comment by mikonvergence** [comment]
> I noticed the latest `a9e0c22` comment is for 'small images'.
> 🫢So I tried `a9e0c22` with:
> <img alt="image" width="1038" src="https://user-images.githubusercontent.com/57209725/195298042-26e901b1-ef3e-45ec-9c0c-22311a209d91.png">
> This input may not be common, so I'm just mentioning it in passing. chill🤗

No, this is quite helpful, thank you! I'll look into this and you can expect another update soon. Then, once it works for all reasonable shapes, we can close this issue.

**Comment by mikonvergence** [comment]
Okay, [eb8a1df](https://github.com/cidcom/SatelliteCloudGenerator/commit/eb8a1dfc35a6adc6328f92f94cd7bc5c55422307) has just been pushed and it contains 2 fixes:

1. The error was due to incorrect multiplication of scales by a non-power-of-2 integer (this multiplication is done to preserve similar cloud appearance regardless of image resolution). Lines 53-54 in `perlin.py` are now fixed and it is guaranteed that the multiplier will be a power of 2.
2. If the user does not want the feature of preserving similar appearance, they can turn it off by setting `const_scale=False` in `add_cloud` or `add_cloud_and_shadow`.
> Intuitively, `const_scale=True` will interpret larger image shapes as higher resolution captures (hence, scale of object is preserved), and `const_scale=False` will interpret larger image shapes as covering more physical area (hence, scale of objects will be reduced with increasing shape).

**Comment by Shiyang980713** [comment]
> Okay, [eb8a1df](https://github.com/cidcom/SatelliteCloudGenerator/commit/eb8a1dfc35a6adc6328f92f94cd7bc5c55422307) has just been pushed and it contains 2 fixes:
> 
> 1. The error was due to incorrect multiplication of scales by a non-power-of-2 integer (this multiplication is done to preserve similar cloud appearance regardless of image resolution). Lines 53-54 in `perlin.py` are now fixed and it is guaranteed that the multiplier will be a power of 2.
> 2. If the user does not want the feature of preserving similar appearance, they can turn it off by setting `const_scale=False` in `add_cloud` or `add_cloud_and_shadow`.
> 
> > Intuitively, `const_scale=True` will interpret larger image shapes as higher resolution captures (hence, scale of object is preserved), and `const_scale=False` will interpret larger image shapes as covering more physical area (hence, scale of objects will be reduced with increasing shape).

I have tested the latest code and no errors are reported. That's awesome, I think this issue can be closed. Thank you again!

**Comment by mikonvergence** [comment]
Brilliant, thank you again for your input!
